tap 'railwaycat/emacsmacport'
tap 'thoughtbot/formulae'
tap 'homebrew/cask-fonts'

brew 'aria2'
brew 'autojump'
brew 'bat'
brew 'coreutils'
brew 'emacs-mac', modules: true
brew 'fish'
brew 'fd'
brew 'gh'
brew 'grep'
brew 'grex'
brew 'htop'
brew 'jq'
brew 'lsd'
brew 'marked'  # markdown compiler
brew 'mpv'
brew 'neovim'
brew 'ripgrep'
brew 'rcm'
brew 'shellcheck'
brew 'switchaudio-osx'
brew 'tarsnap'
brew 'tree'
brew 'wget'

cask 'alfred'
cask 'anki'
cask 'istat-menus'
cask 'dropbox'
cask 'homebrew/cask-fonts/font-source-code-pro-for-powerline'
cask 'gitup'
cask 'google-chrome'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'keycastr'
cask 'mullvadvpn'
cask 'muzzle'
cask 'pastebot'
cask 'qbittorrent'
cask 'rectangle'
cask 'skitch'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'telegram'
cask 'the-unarchiver'

mas 'Keynote', id: 409183694
mas 'Xcode', id: 497799835
mas 'Ivory', id: 6444602274
