tap 'thoughtbot/formulae'
tap 'd12frosted/emacs-plus'
tap 'caskroom/fonts'

brew 'aria2'
brew 'autojump'
brew 'emacs-plus', link: true
brew 'fish'
brew 'graphviz', args: ['with-app']
brew 'htop'
brew 'jq'
brew 'pyenv'
brew 'q'
brew 'rcm'
brew 'tarsnap'
brew 'the_platinum_searcher'
brew 'tree'
brew 'neovim'
brew 'wget'

cask 'alfred'
cask 'anki'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'gitup'
cask 'google-chrome'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'java'
cask 'jetbrains-toolbox'
cask 'jumpcut'
cask 'keycastr'
cask 'omnifocus'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'the-unarchiver'
cask 'telegram'
cask 'transmit'
cask 'vagrant'
cask 'vmware-fusion'

mas 'SSH Tunnel', id: 734418810
mas 'Keynote', id: 409183694
mas 'Growl', id: 467939042

