#!/bin/bash
# The goal of this script is to configure all the things I do whenever I setup a new mac through 
# NOTE: many of these settings won't immediately take effect unless you reboot

# Always show the scrollbar so I don't have to guess which areas are scrollable on websites
defaults -currentHost write -globalDomain AppleShowScrollBars -string Always
